### ISSUE TITLE
このリポジトリのアクセス権限

### ISSUE THREAD

**Issue by y-yu** [rust-lang-ja/trpl-ja-pdf#1]
@KeenS さん。

もうしわけないのですが、このリポジトリ（trpl-ja-pdf）に対する管理者権限を頂けないでしょうか。Travis CIと連携させるためには、管理者権限が必要なので、よろしくおねがいします。
（cc @tatsuya6502）

**Comment by KeenS** [comment]
@y-yu 只今管理権限を付与しました。（以前、Collaboratorに追加しましたがWriteまでしか与えてなかったようでした。)

**Comment by y-yu** [comment]
確認しました。ありがとうございます。
