### ISSUE TITLE
TravisのUbuntu 14.04環境でPDFが生成できない (Undefined control sequence \patchcmd)

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/trpl-ja-pdf#4]
git submoduleの自動アップデートの対応に先立って、[フォークしたレポジトリ](https://github.com/tatsuya6502/trpl-ja-pdf)でTravisでのビルドに挑戦してみました。ところが、以下のエラーが発生し、PDF（A4.PDF、LETTER.PDF）の生成ができません。

https://travis-ci.org/tatsuya6502/trpl-ja-pdf/builds/205243802

```
pandoc: Error producing PDF from TeX source.
! Undefined control sequence.
l.281 \patchcmd
```

デバッグ用にと、クラウド上にUbuntu 14.04環境を用意したところ、そちらでも同じエラーが再現できました。その環境では、.travis.ymlを参考に、以下の２つのスクリプトを実行しました。

- [trpl-ja-install.sh](https://gist.github.com/tatsuya6502/0c5a15c6c2d1d5917fe0ba9d7e3e303c#file-trpl-ja-install-sh)
- [trpl-ja-run.sh](https://gist.github.com/tatsuya6502/0c5a15c6c2d1d5917fe0ba9d7e3e303c#file-trpl-ja-run-sh)

再現はできたものの、pandocに詳しくないので、原因をどのように調査したらよいものか悩んでます。アドバイスをいただけると助かります。

また、調査に必要でしたら、デバッグ用の環境をお貸しします。その場合は、sshアクセスのための公開鍵を教えてください。

**Comment by y-yu** [comment]
ちょっと私の方でもやってみたところ再現するようですが、パッと解決できなさそうです。少々時間をいただきたいと思います。

**Comment by tatsuya6502** [comment]
調査していただき、ありがとうございます。お手数をおかけしますが、よろしくお願いします。

**Comment by y-yu** [comment]
@tatsuya6502 さん。

#5 で直ったと思いますので、こちらで試していただけないでしょうか。

**Comment by tatsuya6502** [comment]
@y-yu ありがとうございます！ 最新の mater で試したところ、エラーが出なくなり、PDFファイルが作成されることが確認できました。

https://travis-ci.org/tatsuya6502/trpl-ja-pdf/builds/208580791
```
...
The command "cargo run --release" exited with 0.

$ cp dist/*a4.pdf ../a4.pdf
The command "cp dist/*a4.pdf ../a4.pdf" exited with 0.

$ cp dist/*letter.pdf ../letter.pdf
The command "cp dist/*letter.pdf ../letter.pdf" exited with 0.
```
